server:
  port: 8050
spring:
  datasource: #数据源配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.95.110.151:3389/erpsystem?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: erpsystem
    password: 123456
    druid:
      max-active: 10
      min-idle: 5
      max-wait: 10000
      initial-size: 5
      validation-query: select 1
      stat-view-servlet:
        enabled: true
#        login-username: admin
#        login-password: admin
#        allow:
#        deny:
        url-pattern: "/druid/*"
        allow: 47.95.110.151
      web-stat-filter:
        enabled: true
        url-pattern: "/druid/**"
        exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
        principal-session-name: ''
        session-stat-enable: true
        session-stat-max-count: 1000
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #redis
  redis:
    host: www.swordman.top
    password: 123456
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        min-idle: 0
        max-wait: 5000


#shiro的配置
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  login-url: /index.html
  unauthorized-url: /unauthorized.html
  anon-urls:
    - /api/login/doLogin*
    - /api/druid/**
    - /api/swagger-ui.html
    - /api/webjars/**
    - /api/swagger-resources/**
    - /api/v2/**
    - /api/login/captcha
    - /api/login/checkLogin
  logout-url: /api/login/logout*
  authc-urls:
    - /**
#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*/*Mapper.xml


#fastdfs设置
fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 5000   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - www.swordman.top:22122
upload:
  base-url: www.swordman.top:8010/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp